-- MySQL Script generated by MySQL Workbench
-- vie 13 nov 2020 21:12:02 WET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema vivero
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema vivero
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vivero` ;
USE `vivero` ;

-- -----------------------------------------------------
-- Table `vivero`.`vivero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`vivero` (
  `ubicacion` TEXT(40) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `hora_apertura` TIME NOT NULL,
  `hora_cierre` TIME NOT NULL,
  PRIMARY KEY (`ubicacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`zonas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`zonas` (
  `nombre` VARCHAR(20) NOT NULL,
  `ubicacion_vivero` TEXT(80) NOT NULL,
  PRIMARY KEY (`nombre`),
  INDEX `ubicacion_vivero` (`ubicacion_vivero` ASC) VISIBLE,
  CONSTRAINT `ubicacion_vivero`
    FOREIGN KEY (`ubicacion_vivero`)
    REFERENCES `vivero`.`vivero` (`ubicacion`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`empleado` (
  `dni` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `codigo_segguridad_social` VARCHAR(45) NOT NULL,
  `tipo_contrato` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dni`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`zonas_empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`zonas_empleado` (
  `dni_empleado` VARCHAR(10) NOT NULL,
  `nombre_zona` VARCHAR(45) NOT NULL,
  `fecha_inicial` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  PRIMARY KEY (`dni_empleado`, `nombre_zona`),
  INDEX `nombre_zona` (`nombre_zona` ASC) VISIBLE,
  CONSTRAINT `dni`
    FOREIGN KEY (`dni_empleado`)
    REFERENCES `vivero`.`empleado` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre`
    FOREIGN KEY (`nombre_zona`)
    REFERENCES `vivero`.`zonas` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`producto` (
  `nombre` VARCHAR(20) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `precio` INT NOT NULL,
  `codigo_de_barra` INT NOT NULL,
  `stock` INT NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`zona_producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`zona_producto` (
  `nombre_zona` VARCHAR(45) NOT NULL,
  `nombre_producto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombre_zona`, `nombre_producto`),
  INDEX `nombre_producto_idx` (`nombre_producto` ASC) VISIBLE,
  CONSTRAINT `nombre_zona`
    FOREIGN KEY (`nombre_zona`)
    REFERENCES `vivero`.`zonas` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `nombre_producto`
    FOREIGN KEY (`nombre_producto`)
    REFERENCES `vivero`.`producto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`cliente` (
  `nombre` VARCHAR(30) NOT NULL,
  `bonificacion` INT NOT NULL,
  `gasto_mensual` INT NOT NULL,
  `numero_tarjeta` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`nombre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`pedido` (
  `fecha` DATE NOT NULL,
  `nombre_cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`fecha`),
  INDEX `nombre_cliente` (`nombre_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_1`
    FOREIGN KEY (`nombre_cliente`)
    REFERENCES `vivero`.`cliente` (`nombre`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`producto_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`producto_pedido` (
  `nombre_producto` VARCHAR(15) NOT NULL,
  `fecha_pedido` DATE NOT NULL,
  PRIMARY KEY (`nombre_producto`, `fecha_pedido`),
  INDEX `fecha_pedido` (`fecha_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_producto_pedido_1`
    FOREIGN KEY (`nombre_producto`)
    REFERENCES `vivero`.`producto` (`nombre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_pedido_2`
    FOREIGN KEY (`fecha_pedido`)
    REFERENCES `vivero`.`pedido` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vivero`.`empleado_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `vivero`.`empleado_pedido` (
  `dni` VARCHAR(10) NOT NULL,
  `fecha_pedido_EP` DATE NOT NULL,
  PRIMARY KEY (`dni`, `fecha_pedido_EP`),
  INDEX `fecha_pedido` (`fecha_pedido_EP` ASC) VISIBLE,
  CONSTRAINT `fk_empleado_pedido_1`
    FOREIGN KEY (`dni`)
    REFERENCES `vivero`.`empleado` (`dni`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_empleado_pedido_2`
    FOREIGN KEY (`fecha_pedido_EP`)
    REFERENCES `vivero`.`pedido` (`fecha`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
